name: GET http request

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: get request
        run: curl https://dummyjson.com/products/1
